### ISSUE TITLE
Does scalastyle work in multi-project sbt setup?

### ISSUE THREAD

**Issue by dbtsai** [scalastyle/scalastyle-sbt-plugin#7]
I created a multi-project SBT build project, 
http://www.scala-sbt.org/release/docs/Getting-Started/Multi-Project

and after running sbt scalastyle, I got
Processed 0 file(s)
Found 0 errors
Found 0 warnings
Finished in 3 ms

In SBT shell, scala-source showed all the soruce code folder correctly. PS, it works for single project setup. 

> scala-source
[info] core/compile:scala-source
[info] 	/Users/dbtsai/dev/alpineml/core/src/main/scala
[info] datasets/compile:scala-source
[info] 	/Users/dbtsai/dev/alpineml/datasets/src/main/scala
[info] root/compile:scala-source
[info] 	/Users/dbtsai/dev/alpineml/src/main/scala

Thanks.

**Comment by nightwolfzor** [comment]
Is it possible to merge the checkstyle/scalastyle-result.xml files when in multi module for reporting to something like Jenkins???

**Comment by matthewfarwell** [comment]
It is not currently possible, but it should be easy enough to write something. Lots of CI systems like jenkins already do merges.

**Comment by Lykathia** [comment]
Can confirm both 0.6.0 and 0.7.0 work mostly fine w/ multiproject builds. There is a little bit of noise w/ scalastyle repeating that it is using the same config over and over at the beginning, but both that and aggregation are separate issues unto themselves.

Safe to close?

**Comment by matthewfarwell** [comment]
Ok. I 'll close this, and if it still there are more problems, then we can open a new issue.

**Comment by jhn** [comment]
@matthewfarwell Can you refer me to a specific Jenkins merge? Currently I'm using the scalastyle jenkins plugin and because multiple files are generated for each of my projects, it's confusing to set the thresholds for failing builds: Does the threshold refer to a single project? The one with the highest number of warnings/errors? Etc. I think I'd be useful to have the option to generate a single aggregated report. If there is interest, I can whip something up.

**Comment by matthewfarwell** [comment]
@jhn You should be able to do something with "Publish Checkstyle analysis results". Scalastyle follows checkstyle format for the xml files, so that should work.
